# Generated by Django 5.2 on 2025-06-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('gl', 'Galician')], default='en', max_length=10),
        ),
    ]
