# Generated by Django 5.2 on 2025-06-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('gl', 'Galician')], default='en', max_length=10),
        ),
    ]
