# Generated by Django 5.2 on 2025-06-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
