# Generated by Django 5.2 on 2025-07-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_profile_is_otp_verified_profile_otp_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
